### ISSUE TITLE
Error with update.cmd

### ISSUE THREAD

**Issue by mime-r** [KayleMine/wor-tortle#3]
I added the folder "update" in the main directory as you've stated (After adding Lib into pyp directory). However, the code gives the following error:

'charmap' codec can't encode characters in position 388-399: character maps to <undefined>
Traceback (most recent call last):
  File "C:\Users\...\wor-tortle-main\pyp\modules.py", line 96, in load_modules
    load_module(update_path, modules_data, 'functions.maths')
  File "C:\Users\...\wor-tortle-main\pyp\modules.py", line 73, in load_module
    module_file.write(module_code)
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 388-399: character maps to <undefined>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\...\wor-tortle-main\pyp\modules.py", line 125, in <module>
    load_modules()
  File "C:\Users\...\wor-tortle-main\pyp\modules.py", line 123, in load_modules
    exit()
    ^^^^
NameError: name 'exit' is not defined
Press any key to continue . . .

Is there any way to resolve this? Sorry for the inconvenience.

**Comment by KayleMine** [comment]
No issue, problem on your side, did u unpack Lib to pyp folder?

Did you have same struct?:
![image](https://github.com/KayleMine/wor-tortle/assets/60858771/d042ec82-d2a4-4e6e-a08e-a053dcf094d7)
![image](https://github.com/KayleMine/wor-tortle/assets/60858771/0adc83b1-19ad-4148-9eca-2d08c22f0e34)
